Add scripts for local code formatting check
jserv/ttt pull request #15
Opened 2024-01-27 17:34 UTC by freshLiver

This commit use the git pre-commit hook to check and report the code formatting problem in the committed codes. The version of the clang-format is required to be greater than 12 because the use of [`StatementAttributeLikeMacros`](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#statementattributelikemacros).

However, as the directory .git/hooks cannot be tracked by git, additional configuration is required, which is written in the README file.

The reason why not merge the scripts into .githooks/pre-commit is for future expansion (e.g., compilation check and reuse the script for GitHub Action).

2024-01-27 17:38 UTC, jserv requested changes
Enable GitHub Actions with predefined CI pipeline to ensure the consistent style.
See https://github.com/sysprog21/rv32emu/blob/master/.github/workflows/main.yml for reference.

2024-01-27 17:55 UTC, freshLiver commented
Add GitHub action script for checking code formatting. An example is available at [my fork](https://github.com/freshLiver/ttt/pull/1)

2024-01-27 18:02 UTC, jserv commented on README.md
> +## Code Formatting Check
Drop the section "Code Formatting Check."

Instead, I would place contributing guide like https://github.com/sysprog21/rv32emu/blob/master/CONTRIBUTING.md .

2024-01-27 18:04 UTC, jserv requested changes
1. Rename from `scripts/check-format.sh` to `.ci/check-format.sh`
2. Install git pre-commit hook during default target. See https://github.com/sysprog21/lab0-c/blob/master/Makefile#L36
3. Build the default target in CI pipeline.

2024-01-28 08:45 UTC, freshLiver commented
I only apply the hook-related scripts from [the mentioned install-git-hooks script](https://github.com/sysprog21/lab0-c/blob/master/scripts/install-git-hooks). Should the other scripts (e.g., checking whether forked) also be added in this PR?

2024-01-28 08:46 UTC, jserv commented
> I only apply the hook-related scripts from [the mentioned install-git-hooks script](https://github.com/sysprog21/lab0-c/blob/master/scripts/install-git-hooks). Should the other scripts (e.g., checking whether forked) also be added in this PR?

You can submit later. This pull request looks fine.

2024-01-28 08:47 UTC, jserv commented on .github/workflows/main.yml
> +            ./.ci/check-format.sh
Simply run `.ci/check-format.sh` without leading `./` (dot slash).

2024-01-28 09:04 UTC, merged

2024-01-28 09:05 UTC, jserv commented
Thank @freshLiver for contributing!