Display error message for occupied positions
jserv/ttt pull request #27
Opened 2024-02-02 09:33 UTC by paul90317

Display an error message when a player attempts to place a marker (circle/cross) on a position already occupied by another marker.

2024-02-02 09:45 UTC, jserv requested changes
Read https://cbea.ms/git-commit/ carefully and refine the git commit message.

2024-02-02 09:46 UTC, jserv commented on ttt.c
> +                } else {
The `else` statement here is not needed since the previous one is `break`.

2024-02-02 10:22 UTC, paul90317 commented
It seems that I forgot to wrap the body at 72 characters. I have remade the commit message.

2024-02-02 11:23 UTC, jserv commented on ttt.c
> +                    "Invalid operation: O/X already placed at this "
Improve this message. Check https://en.wikipedia.org/wiki/Tic-tac-toe for proper rule description.

2024-02-02 11:27 UTC, jserv requested changes
Refine the Git commit message by formulating it as an unambiguous and complete English sentence.

2024-02-03 00:56 UTC, merged

2024-02-03 00:57 UTC, jserv commented
Thank @paul90317 for contributing!