Add Move Recording and Output Move Sequence
jserv/ttt pull request #5
Opened 2024-01-25 17:58 UTC by kaiweike

## Description
This pull request introduces modifications to enable recording and outputting the sequence of moves.

## Changes
- Implemented `record_move` function to track each move.
- Implemented `print_moves` function to output the sequence of moves.
- Initialized `best_move` to -1 in `negamax` function. This serves as a flag to determine whether a move should be recorded.

2024-01-25 18:05 UTC, jserv commented on ttt.c
> +#define MAX_MOVES 9
Avoid hardcoded literal. Specify `(3 * 3)` instead.

2024-01-25 18:09 UTC, jserv requested changes
Check https://cbea.ms/git-commit/ carefully and rework git commit messages.

2024-01-25 20:34 UTC, kaiweike commented on ttt.c
> +#define MAX_MOVES 9
done

2024-01-25 20:37 UTC, kaiweike commented
Thanks for the suggestions. I have made the following changes:
- Updated the definition of `MAX_MOVES` to avoid hardcoded literal.
- Reworked the git commit messages.

2024-01-26 01:45 UTC, merged

2024-01-26 01:46 UTC, jserv commented
Thank @kaiweike for contributing!