modified: rename negamax function to alpha_beta
jserv/ttt pull request #9
Opened 2024-01-26 12:16 UTC by jouae

Due to changing the original algorithm from negamax to alpha-beta pruning the function name has been modified to "alpha_beta"

2024-01-26 17:08 UTC, jserv commented on README.md
> +Make sure your operating system is **Linux** then use the command in shell
This program is not Linux specific. It runs on macOS and BSD system. All you need is a full functioned terminal emulator.

Drop this section if you tend to submit a pull request to rename `negamax` function.

2024-01-26 17:09 UTC, jserv requested changes
Run `clang-format -i` before submitting.

2024-01-26 17:28 UTC, visitorckw commented
Negamax and alpha-beta pruning are not two opposing algorithms. More precisely, the current implementation utilizes negamax with alpha-beta pruning. Therefore, I am wondering if changing the name might actually decrease the program's readability.

2024-01-26 23:01 UTC, closed without merging

2024-01-26 23:01 UTC, jouae commented
@ndsl7109256 Yes I can understand your considerations. 
Perhaps I can left a comment in the negamax function in the program to explain that is not origin negamax algorithm?

2024-01-27 14:24 UTC, visitorckw commented
I don't have opinions on whether to add comments.
If you believe that comments would be helpful for the code, feel free to do so.